#!/bin/bash -x

CFLAGS="-Wall -nostdinc -mkernel -D_KERNEL -DKERNEL -DKERNEL_PRIVATE -DDRIVER_PRIVATE -DAPPLE -DNeXT -I/Users/lundman/src/zfs/osx.zfs/x/spl/include -I/System/Library/Frameworks/Kernel.framework/PrivateHeaders -I/System/Library/Frameworks/Kernel.framework/Headers "

#gcc $CFLAGS -o spl-atomic.o -c spl-atomic.c
#gcc $CFLAGS -o spl-condvar.o -c spl-condvar.c
#gcc $CFLAGS -o spl-cred.o -c spl-cred.c
##gcc $CFLAGS -o spl-debug.o -c spl-debug.c
#gcc $CFLAGS -o spl-kmem.o -c spl-kmem.c
#gcc $CFLAGS -o spl-kobj.o -c spl-kobj.c
#gcc $CFLAGS -o spl-kstat.o -c spl-kstat.c
#gcc $CFLAGS -o spl-mutex.o -c spl-mutex.c
#gcc $CFLAGS -o spl-proc.o -c spl-proc.c
#gcc $CFLAGS -o spl-rwlock.o -c spl-rwlock.c
gcc $CFLAGS -o splat-osx.o -c splat-osx.c
#gcc $CFLAGS -o spl-taskq.o -c spl-taskq.c
#gcc $CFLAGS -o spl-thread.o -c spl-thread.c
#gcc $CFLAGS -o spl-time.o -c spl-time.c
#gcc $CFLAGS -o spl-vnode.o -c spl-vnode.c
##gcc $CFLAGS -o spl-zlib.o -c spl-zlib.c

mkdir -p splat.kext/Contents/Resources/English.lproj splat.kext/Contents/MacOS
cp -f Info.plist splat.kext/Contents/
cp -f InfoPlist.strings splat.kext/Contents/Resources/English.lproj/

gcc -o splat.kext/Contents/MacOS/splat *.o -Xlinker -kext -nostdlib -lkmodc++ -lkmod -lcc_kext || echo "Linking failed"

kextlibs -undef-symbols -xml splat.kext/ && echo "Build successful"
