#!/bin/sh
PATH=/bin:/usr/bin:/sbin:/usr/sbin:/opt/local/bin
export PATH
export LC_ALL=en_GB.UTF-8

#sysctl vm | egrep '^vm.page_(free_(wanted|count)|speculative|purgeable_count)'
#sysctl kstat.zfs.misc.arcstats.l2_hdr_size kstat.spl | gawk 'sqrt($2*$2) < 1024 { print $1, $2 } \
#        sqrt($2*$2) > 1024 && sqrt($2*$2) < 1024^2 { print $1, $2/1024, "K" } \
#       sqrt($2*$2) > 1024^2 && sqrt($2*$2) < 1024^3 { print $1, $2/1024^2, "M" } \
#       sqrt($2*$2) > 1024^3                { print $1, $2/1024^3, "G" }'

sysctl vm | egrep '^vm.page_(free_(wanted|count)|speculative|purgable_count)' | gnumfmt --field=2 --grouping

sysctl kstat.zfs.misc.arcstats.l2_hdr_size  kstat.zfs.misc.arcstats.arc_no_grow kstat.spl | egrep -v 'spl.reap_timeout|spl_misc.reap_thread|spl_free_(manual|fast)_pressure|spl.*wake_count|spl_spl_minimal_uses_spl_free|vm_page_free_multiplier|vm_page_free_min_min|active_(threads|mutex|rwlock|tsd|reap_thread|reap_timeout_seconds)|spl_osif_.*_calls:.0$|pushpage_waitlimit' | gnumfmt --field=2 --to=iec-i # --grouping

sysctl kstat.vmem.vmem.kmem_va.mem_inuse kstat.vmem.vmem.kmem_default.mem_inuse kstat.vmem.vmem.heap.mem_inuse kstat.vmem.vmem.zfs_file_data.mem_inuse kstat.vmem.vmem.zfs_file_data.mem_import kstat.unix.kmem_cache.zio_cache.buf_inuse kstat.zfs.misc.arcstats.tempreserve kstat.zfs.misc.arcstats.loaned_bytes kstat.vmem.vmem.heap.mem_total kstat.vmem.vmem.zfs_file_data.mem_total kstat.vmem.vmem.zfs_metadata.mem_total kstat.vmem.vmem.spl_root_arena.mem_inuse kstat.vmem.vmem.spl_root_arena.mem_total kstat.vmem.vmem.free_arena.mem_import kstat.vmem.vmem.free_arena.parent_free kstat.vmem.vmem.spl_large_reserve_arena.mem_inuse kstat.vmem.vmem.spl_large_reserve_arena.alloc kstat.vmem.vmem.spl_large_reserve_arena.free kstat.vmem.vmem.xnu_import.mem_inuse kstat.vmem.vmem.xnu_import.mem_import kstat.vmem.vmem.xnu_import.alloc kstat.vmem.vmem.xnu_import.fail | gnumfmt --field=2 --to=iec-i
