#!/bin/sh
PATH=/bin:/usr/bin:/sbin:/usr/sbin:/opt/local/bin
export PATH
export LC_ALL=en_GB.UTF-8

watch -d sysctl -h kstat.vmem.vmem.spl_large_reserve_arena kstat.vmem.vmem.xnu_import  kstat.spl.misc.spl_misc.spl_vmem_free_memory_recycled kstat.spl.misc.spl_misc.spl_vmem_free_memory_released  kstat.spl.misc.spl_misc.vmem_conditional_allocs kstat.spl.misc.spl_misc.ta_xnu_vmem_alloc kstat.spl.misc.spl_misc.ta_xnu_vmem_bytes kstat.spl.misc.spl_misc.ta_xnu_success kstat.spl.misc.spl_misc.ta_xnu_success_bytes kstat.spl.misc.spl_misc.ta_reserve_success kstat.spl.misc.spl_misc.ta_reserve_alloc_bytes kstat.spl.misc.spl_misc.sra_extra_pass kstat.spl.misc.spl_misc.spl_osif_malloc_success kstat.vmem.vmem.spl_root_arena.parent_alloc kstat.vmem.vmem.spl_root_arena.parent_xalloc kstat.vmem.vmem.spl_root_arena.parent_free
