#!/bin/sh
PATH=/bin:/usr/bin:/sbin:/usr/sbin:/opt/local/bin
export PATH
export LC_ALL=en_GB.UTF-8

watch -d sysctl -h kstat.vmem.vmem.zfs_file_data kstat.vmem.vmem.zfs_metadata kstat.vmem.vmem.spl_root_arena.mem_inuse kstat.vmem.vmem.spl_root_arena.mem_total kstat.vmem.vmem.spl_root_arena.alloc kstat.vmem.vmem.spl_root_arena.free kstat.vmem.vmem.spl_root_arena.lookup kstat.vmem.vmem.spl_root_arena.search kstat.vmem.vmem.spl_root_arena.parent_alloc kstat.vmem.vmem.spl_root_arena.parent_xalloc kstat.vmem.vmem.spl_root_arena.parent_free kstat.spl.misc.spl_misc.spl_osif_malloc_success kstat.spl.misc.spl_misc.spl_osif_free kstat.spl.misc.spl_misc.os_mem_alloc kstat.spl.misc.spl_misc.spl_spl_free kstat.unix.kmem_cache.kmem_slab_cache.reap
