#!/bin/bash -x -e

PARENT_DIR=$(dirname "$0")
cd "$PARENT_DIR"/../..
ABS_PATH="$(pwd)"
cd - >/dev/null
echo $ABS_PATH

CFLAGS="-Wall -nostdinc -mkernel -D_KERNEL -DKERNEL -DKERNEL_PRIVATE -DDRIVER_PRIVATE -DAPPLE -DNeXT -I$ABS_PATH/include -I/System/Library/Frameworks/Kernel.framework/PrivateHeaders -I/System/Library/Frameworks/Kernel.framework/Headers "

gcc $CFLAGS -o spl-xdr.o -c spl-xdr.c

gcc $CFLAGS -o spl-atomic.o -c spl-atomic.c
gcc $CFLAGS -o spl-condvar.o -c spl-condvar.c
gcc $CFLAGS -o spl-cred.o -c spl-cred.c
gcc $CFLAGS -o spl-err.o -c spl-err.c
##gcc $CFLAGS -o spl-debug.o -c spl-debug.c
gcc $CFLAGS -o spl-kmem.o -c spl-kmem.c
gcc $CFLAGS -o spl-kobj.o -c spl-kobj.c
gcc $CFLAGS -o spl-kstat.o -c spl-kstat.c
gcc $CFLAGS -o spl-list.o -c spl-list.c
gcc $CFLAGS -o spl-mutex.o -c spl-mutex.c
gcc $CFLAGS -o spl-proc.o -c spl-proc.c
gcc $CFLAGS -o spl-rwlock.o -c spl-rwlock.c
gcc $CFLAGS -o spl-osx.o -c spl-osx.c
gcc $CFLAGS -o spl-taskq.o -c spl-taskq.c
gcc $CFLAGS -o spl-thread.o -c spl-thread.c
gcc $CFLAGS -o spl-time.o -c spl-time.c
gcc $CFLAGS -o spl-vnode.o -c spl-vnode.c
gcc $CFLAGS -o spl-xdr.o -c spl-xdr.c
##gcc $CFLAGS -o spl-zlib.o -c spl-zlib.c

mkdir -p spl.kext/Contents/Resources/English.lproj spl.kext/Contents/MacOS
cp -f Info.plist spl.kext/Contents/
cp -f InfoPlist.strings spl.kext/Contents/Resources/English.lproj/

gcc -o spl.kext/Contents/MacOS/spl *.o -Xlinker -kext -nostdlib -lkmodc++ -lkmod -lcc_kext || echo "Linking failed"

kextlibs -undef-symbols -xml spl.kext/ && echo "Build successful"
